CREATE TABLE country (
	id TINYINT AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(45) NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


CREATE TABLE state(
	id SMALLINT AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(45) NOT NULL,
	shortname VARCHAR(2) NOT NULL,
	
	id_country TINYINT,
	
	FOREIGN KEY (id_country) REFERENCES country(id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE city(
	id SMALLINT AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(80) NOT NULL,
	idibge VARCHAR(15) NOT NULL,
		
	id_state SMALLINT NOT NULL,
	
	FOREIGN KEY (id_state) REFERENCES state(id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


CREATE TABLE neighborhood(
	id MEDIUMINT AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(80) NOT NULL,
	
	id_city SMALLINT,
	
	FOREIGN KEY (id_city) REFERENCES city(id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE street(
	id MEDIUMINT AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(100),
	cep VARCHAR(8),
	complement VARCHAR(100),
	type_adress VARCHAR(15),
	
	id_neighborhood MEDIUMINT,
	
	FOREIGN KEY (id_neighborhood) REFERENCES neighborhood(id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
